'use strict';
const DATA=window.REVIEW_DATA,Q=DATA.rows,byId=new Map(Q.map(q=>[q.id,q])),KEY='chinese-garden-v1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activeKey=KEY;
let db={version:1,current:null,users:[]},view='home',category='全部',search='',pageIndex=0,sourceDoc=2,sourcePage=2,showAllAnswers=false,wrongAll=false,lastTick=Date.now(),storageOK=true;
try{const old=JSON.parse(localStorage.getItem(KEY)||'null');if(old&&old.version===1&&Array.isArray(old.users))db=old;}catch(e){storageFail('無法讀取先前資料。請匯入備份；目前新紀錄仍可嘗試儲存。');}
function storageFail(msg){storageOK=false;$('#storageWarning').hidden=false;$('#storageWarning').textContent='⚠️ '+msg;}
function persist(){let saved=true;try{localStorage.setItem(activeKey,JSON.stringify(db));storageOK=true;$('#storageWarning').hidden=true;}catch(e){saved=false;storageFail('瀏覽器無法儲存紀錄，請立即匯出備份，以免關閉後遺失。');}window.GardenCloud?.changed();return saved;}
function user(){return db.users.find(x=>x.name===db.current)||null;}
function fresh(name){return {name,learned:[],wrong:{},history:[],session:null};}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').style.display='none',2600);}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function requireUser(){if(user())return true;openLogin();return false;}
function updateUser(){const u=user();$('#userButton').textContent=u?'🌻 '+u.name:'👋 姓名登入';}
function confirmAction(title,text,fn){$('#confirmTitle').textContent=title;$('#confirmText').textContent=text;$('#confirmDialog').showModal();$('#confirmNo').onclick=()=>$('#confirmDialog').close();$('#confirmYes').onclick=()=>{$('#confirmDialog').close();fn();};}
function openLogin(){$('#existingUsers').innerHTML=db.users.map((u,i)=>`<button type="button" data-login-index="${i}">🌱 ${esc(u.name)}</button>`).join('');$('#login').showModal();$('#nameInput').focus();}
function login(name){if(window.GardenCloud){window.GardenCloud.select(name);return;}name=name.trim().normalize('NFC');if(!name||name.length>30)return;pause(false);if(!db.users.some(u=>u.name===name))db.users.push(fresh(name));db.current=name;persist();$('#login').close();updateUser();navigate('home');toast('歡迎，'+name+'！');}
$('#loginForm').onsubmit=e=>{e.preventDefault();login($('#nameInput').value);};$('#login .close').onclick=()=>$('#login').close();$('#userButton').onclick=()=>user()?navigate('profile'):openLogin();
function tick(){let s=user()?.session,now=Date.now();if(s&&!s.paused&&!s.done){s.elapsed+=Math.max(0,Math.min(now-lastTick,60000));}lastTick=now;}
function pause(notify=true){tick();const s=user()?.session;if(s&&!s.done){s.paused=true;const ok=persist();if(notify)toast(ok?'⏸️ 已暫停，進度已儲存':'已暫停，請匯出備份');}}
function navigate(v){if(view==='quiz'&&v!=='quiz')pause(false);view=v;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===v));render();window.scrollTo({top:0,behavior:'instant'});}
function title(emoji,t,sub){return `<div class="page-title"><div class="eyebrow">${emoji} YOUR LEARNING GARDEN</div><h1>${t}</h1><p class="muted">${sub}</p></div>`;}
function render(){updateUser();const f={home,learn,quiz,wrong,sources,fill,profile,print:printPage};$('#main').innerHTML=(f[view]||home)();bindPage();window.GardenCloud?.paint();}
const topicDefs=[['國字注音','🔤','國字注音練習','原卷 1～135 題，多空格逐一練習。','lilac'],['填充解答','📝','課文重點・填充解答','〈土〉、詞選、921 與大明湖，一次補齊。','peach'],['形音義','🧩','形音義與多音字','相近字形、不同字義，拆開記更清楚。','butter'],['詞學','🌙','詞學與詩詞比較','詞牌、格律、婉約豪放與兩闋詞。','blue'],['人物聯','🧧','對聯小偵探','從關鍵字辨人物，也認識各行各業。','mint'],['報導文學','🌏','文學知識補給站','鄉土詩、報導文學與小說流變。','peach']];
function activeWrong(u=user()){return u?Object.keys(u.wrong).filter(id=>byId.has(id)&&u.wrong[id].streak<2):[];}
function home(){let u=user(),done=u?.learned.length||0,hs=u?.history||[],avg=hs.length?Math.round(hs.reduce((a,h)=>a+h.score,0)/hs.length):0;return (window.GardenCloud?.panel()||'')+`<section class="hero"><div><span class="tag">✨ 國三上學期・第一次段考</span><h1>把國文讀成<br>一座小花園 🌷</h1><p>字音一點點熟悉，詩詞一首首讀懂。<br>帶著好奇心，把每一道不會的題目，變成會開花的知識。</p><div class="actions"><button class="primary" data-nav="learn">開始複習 →</button><button data-nav="quiz">🎯 來場小測驗</button><button data-nav="print">🖨️ 手寫考卷</button></div></div><div class="garden" aria-hidden="true"><span class="sun">☀️</span><span class="speech">今天也長出一點點知識！</span><div class="book">📖</div><div class="plants">🌷🌱🌼</div></div></section><div class="stats"><div class="stat"><strong>4</strong>份<span class="muted">完整教材・共 8 頁</span></div><div class="stat"><strong>${Q.length}</strong>題<span class="muted">全選擇題練習庫</span></div><div class="stat"><strong>${done}</strong>張<span class="muted">我的已讀學習卡</span></div><div class="stat"><strong>${activeWrong().length}</strong>題<span class="muted">等待澆水的錯題 🌱</span></div></div>${u?.session&&!u.session.done?`<div class="banner"><div><h3>📌 你的進度還在這裡</h3><p>已答 ${Object.keys(u.session.answers).length} / ${u.session.ids.length} 題，隨時可以接著做。</p></div><button class="primary" data-action="resume">繼續上次測驗 →</button></div>`:''}<div class="section-head"><h2>今天，想從哪裡開始？</h2><span class="muted">六條學習小徑，慢慢探索 🌿</span></div><div class="grid">${topicDefs.map(([cat,icon,t,sub,color])=>`<button class="card topic" data-topic="${cat}"><span class="icon ${color}">${icon}</span><h3>${t}</h3><p>${sub}</p><span class="count">${topicRows(cat).length} 張知識卡</span><span class="arrow">↗</span></button>`).join('')}</div><div class="banner"><div><h3>📝 那張沒有答案的填充卷，補好了！</h3><p>重點彙整 1 第 2 頁：逐空解答、兩闋詞全文與老師的小提醒。</p></div><button data-nav="fill">翻開解答本 →</button></div><div class="section-head"><h2>🌼 我的成長紀錄</h2><button class="tiny" data-nav="profile">查看與備份</button></div><div class="card"><div class="meter-label"><span>教材掌握進度</span><span>${done} / ${Q.length} 張已讀</span></div><div class="progress"><span style="width:${done/Q.length*100}%"></span></div><p class="muted" style="margin:0">${u?`已完成 ${hs.length} 次測驗${hs.length?'，平均 '+avg+' 分':''}。錯題連續答對兩次，就會移入已掌握區。`:'登入姓名後，就能收藏已讀進度、累積成績與保存錯題。'}</p></div>`;}
function topicRows(cat){const groups={'填充解答':['填充解答','詩詞默寫'],'形音義':['形音義','字音義'],'詞學':['詞學','詞派','詩詞比較','詩詞默寫'],'人物聯':['人物聯','行業聯','對聯常識'],'報導文學':['報導文學','鄉土詩','小說流變']};return Q.filter(q=>(groups[cat]||[cat]).includes(q.cat));}
function filtered(){return Q.filter(q=>(matchesCategory(q,category))&&(!search||[q.prompt,q.answer,q.explain,q.ref].join(' ').toLowerCase().includes(search.toLowerCase())));}
function learn(){const list=filtered();return title('📚','學習小徑','依教材原編號排列，全部答案與解析直接展開。往下滑就能讀完整個單元。')+`<div class="toolbar"><input class="search" id="search" aria-label="搜尋學習內容" placeholder="🔎 搜尋字詞、作者、原題號…" value="${esc(search)}"><select id="category" aria-label="選擇學習單元">${categories().map(c=>`<option ${c===category?'selected':''}>${c}</option>`).join('')}</select><button data-action="practiceFiltered">🎯 測驗本範圍全部題目</button><button data-nav="print">🖨️ 手寫考卷</button></div><p class="section-note">${esc(category)} · 共 ${list.length} 張 · 依原資料順序完整顯示</p><div class="learn-list waterfall">${list.map(cardHTML).join('')||'<div class="empty full">🔎 找不到符合的內容，換個關鍵字試試。</div>'}</div>`;}
function matchesCategory(q,c){return c==='全部'||q.cat===c||'國字注音・'+q.unit===c||(c.startsWith('主題・')&&topicRows(c.slice(3)).some(x=>x.id===q.id));}
function categories(){return ['全部',...topicDefs.map(t=>'主題・'+t[0]),...new Set(Q.map(q=>q.cat)),...['土','詞選','與921說再見','對聯','大明湖'].map(u=>'國字注音・'+u)];}
function cardHTML(q){const read=user()?.learned.includes(q.id);return `<article class="card learn-card ${read?'learned':''}"><div class="ref"><span>${esc(q.sourceLabel||q.ref)}</span><a href="#source-${q.doc}-${q.page}" data-source="${q.doc},${q.page}">查看原頁 ↗</a></div><p class="task-label">${esc(q.task||q.cat)}</p><h3 class="source-prompt">${esc(q.prompt)}</h3><div class="answer">✅ 答案：${esc(q.answer)}</div><div class="explain"><strong>📖 解析與辨析</strong><p>${esc(q.explain)}</p></div><button data-learned="${q.id}" aria-pressed="${!!read}">${read?'✅ 已讀懂':'🌱 標記已讀'}</button></article>`;}
function setupQuiz(){return title('🎯','整個單元，一起練習','依原卷題號與表格順序出題；一次顯示全部題目，選答後立即顯示對錯與完整解析。')+`<section class="card quiz-setup"><div class="bigemoji">🧸</div><h2>今天要複習哪個單元？</h2><label for="quizCategory">練習範圍</label><select id="quizCategory" style="display:block;width:100%;margin:10px 0 20px">${categories().map(c=>`<option>${c}</option>`).join('')}</select><div class="notice">選定單元的全部題目會依原順序列出。可自由往下作答；每題選答即儲存、顯示對錯與解析。得分＝答對題數 ÷ 本次全部題數 × 100。</div><div class="actions"><button class="primary" data-action="start">開始完整單元測驗 🌱</button><button data-nav="wrong">🌱 打開錯題本</button></div></section>`;}
function sessionOptions(s,id){return s.optionBank?.[id]||(s.bankRevision===DATA.quizRevision?byId.get(id).options:(DATA.legacyOptions?.[id]||byId.get(id).options));}
function prepareSession(s){if(s.sourceOrder===DATA.quizRevision)return;const current=s.ids[s.index];s.ids.sort((a,b)=>byId.get(a).sourceIndex-byId.get(b).sourceIndex);s.index=Math.max(0,s.ids.indexOf(current));s.bankRevision=s.bankRevision||'legacy-v1';s.sourceOrder=DATA.quizRevision;persist();}
function quizSummary(s){const answered=Object.keys(s.answers).length,correct=Object.values(s.answers).filter(a=>a.correct).length;return `<div><strong>📝 已答 ${answered} / ${s.ids.length}</strong><span>✅ 答對 ${correct} 題 · 得分 ${Math.round(correct/s.ids.length*100)} 分</span><span>⏱ <span id="timer">${formatTime(s.elapsed)}</span></span></div><div class="actions"><button data-action="pause">⏸ 暫停並儲存</button><button data-action="firstUnanswered">找下一題未答 ↓</button><button class="primary" data-action="finish">完成並看成績</button></div>`;}
function quizQuestion(s,id,i){const q=byId.get(id),a=s.answers[id],opts=sessionOptions(s,id),answerText=opts[0],modern=s.bankRevision===DATA.quizRevision;return `<article class="card quiz-card stream-question" id="quiz-${id}" data-question-card="${id}"><div class="ref"><strong>${esc(q.sourceLabel||q.ref)}</strong><a data-source="${q.doc},${q.page}" href="#source-${q.doc}-${q.page}">查看原頁 ↗</a></div><p class="task-label">本單元 ${i+1} / ${s.ids.length} · ${esc(q.task||'選擇原資料對應答案')}</p><h2 class="source-prompt">${esc(q.prompt)}</h2><div class="options">${s.order[id].map((opt,j)=>`<button class="option ${a?(opt===0?'correct':opt===a.choice?'incorrect':''):''}" data-question="${id}" data-choice="${opt}" ${a?'disabled':''}><span class="letter">${'ABCD'[j]}</span><span>${esc(opts[opt])}</span>${a&&opt===0?'<span aria-label="正確答案">✓</span>':''}${a&&opt===a.choice&&opt!==0?'<span aria-label="你的錯誤答案">✕</span>':''}</button>`).join('')}</div>${a?`<section class="feedback ${a.correct?'':'bad'}" role="status" tabindex="-1"><strong>${a.correct?'✅ 答對了！':'❌ 這題答錯了，一起看清楚。'}</strong><p>你的答案：${esc(opts[a.choice])}<br><b>正確答案：${esc(answerText)}</b></p><div class="explain"><strong>📖 完整解析</strong><p>${esc(q.explain)}</p>${modern?`<ul class="option-analysis">${s.order[id].map((opt,j)=>`<li><b>${'ABCD'[j]}. ${esc(opts[opt])}</b>：${esc(q.optionNotes?.[opt]||'請依原資料答案核對。')}</li>`).join('')}</ul>`:'<p>這次為更新前開始的測驗，保留當時的選項與作答紀錄。另開測驗即可使用新版近似選項。</p>'}</div></section>`:'<p class="muted">選一個答案後立即批改；本次同一題只能作答一次。</p>'}</article>`;}
function quiz(){const s=user()?.session;if(!s)return setupQuiz();prepareSession(s);if(s.done)return result(s);if(s.paused)return title('⏸️','休息一下，進度都在','回來後仍會完整顯示本次題目，已作答的解析也會保留。')+`<div class="card center"><div class="bigemoji">🫖</div><h2>${esc(s.label)}</h2><p>已答 ${Object.keys(s.answers).length} / ${s.ids.length} 題 · 累計 ${formatTime(s.elapsed)}</p><div class="actions" style="justify-content:center"><button class="primary" data-action="resume">▶️ 繼續測驗</button><button data-action="newQuiz">另開完整單元測驗</button><button data-action="export">💾 匯出備份</button></div></div>`;return title('🎯',esc(s.label),'按教材原順序往下作答；每道題目都會原地顯示批改結果與解析。')+`<section id="quizSummary" class="quiz-summary" aria-label="測驗進度">${quizSummary(s)}</section>${s.bankRevision!==DATA.quizRevision?'<p class="notice">這是更新前保留的測驗範圍。已依原題序重排，作答與選項仍完整保留；另開測驗會列出該單元全部題目。</p>':''}<div class="quiz-stream waterfall">${s.ids.map((id,i)=>quizQuestion(s,id,i)).join('')}</div><div class="actions quiz-end"><button class="primary" data-action="finish">完成全部作答，查看成績 🌷</button><button data-action="pause">⏸ 暫停並儲存</button></div>`;}
function scrollQuestion(id){const el=$('#quiz-'+id);el?.scrollIntoView?.({behavior:'smooth',block:'center'});}
function firstUnanswered(){const s=user()?.session;if(!s)return;const id=s.ids.find(id=>!s.answers[id]);if(id){s.index=s.ids.indexOf(id);persist();scrollQuestion(id);}else toast('全部答完了，可以查看成績！');}
function formatTime(ms){let sec=Math.floor(ms/1000);return `${Math.floor(sec/60)} 分 ${sec%60} 秒`;}
function startSession(list,label,count){if(!requireUser())return;if(!list.length){toast('這個範圍目前沒有題目。');return;}const run=()=>{const ids=[...new Set(list.map(q=>q.id))].sort((a,b)=>byId.get(a).sourceIndex-byId.get(b).sourceIndex);const order={};ids.forEach(id=>order[id]=shuffle([0,1,2,3]));user().session={ids,order,label,index:0,answers:{},elapsed:0,paused:false,done:false,started:new Date().toISOString(),bankRevision:DATA.quizRevision,sourceOrder:DATA.quizRevision};lastTick=Date.now();persist();navigate('quiz');};if(user().session&&!user().session.done)confirmAction('開始新的完整單元測驗？','目前這次尚未完成。新測驗會取代它的未完成進度；已記錄的錯題與過往成績會保留。',run);else run();}
function answer(choice,questionId){const u=user(),s=u?.session;if(!s||s.paused||s.done||!Number.isInteger(choice)||choice<0||choice>3)return;const id=questionId||s.ids[s.index];if(!s.ids.includes(id)||s.answers[id])return;const opts=sessionOptions(s,id);tick();s.index=s.ids.indexOf(id);const correct=choice===0;s.answers[id]={choice,correct};if(!correct){const w=u.wrong[id]||{count:0,streak:0};w.count++;w.streak=0;w.last=opts[choice];w.at=new Date().toISOString();u.wrong[id]=w;}else if(u.wrong[id])u.wrong[id].streak=Math.min(2,u.wrong[id].streak+1);persist();const article=$('#quiz-'+id),summary=$('#quizSummary');if(article&&view==='quiz'){article.outerHTML=quizQuestion(s,id,s.index);if(summary)summary.innerHTML=quizSummary(s);$('#quiz-'+id+' .feedback')?.focus?.({preventScroll:true});}else render();}
function finish(){const s=user()?.session;if(!s||s.done)return;const missing=s.ids.filter(id=>!s.answers[id]);if(missing.length){toast(`還有 ${missing.length} 題未答，已定位第一題未答題。`);s.index=s.ids.indexOf(missing[0]);persist();scrollQuestion(missing[0]);return;}tick();s.done=true;s.paused=true;s.score=Math.round(Object.values(s.answers).filter(a=>a.correct).length/s.ids.length*100);user().history.unshift({at:new Date().toISOString(),label:s.label,total:s.ids.length,correct:Object.values(s.answers).filter(a=>a.correct).length,score:s.score,elapsed:s.elapsed});persist();render();window.scrollTo({top:0,behavior:'instant'});}
function result(s){const wrongIds=s.ids.filter(id=>!s.answers[id].correct);return title('🌷','又完成一段成長旅程！','分數幫你看見進度，錯題幫你找到下一步。')+`<section class="card center"><div class="bigemoji">${s.score===100?'🏆':'🌻'}</div><div class="result-number">${s.score}<span style="font-size:20px"> 分</span></div><p>答對 ${s.ids.length-wrongIds.length} / ${s.ids.length} 題 · ${formatTime(s.elapsed)}</p><div class="actions" style="justify-content:center"><button class="primary" data-action="retrySessionWrong" ${wrongIds.length?'':'disabled'}>🌱 重練本次錯題（${wrongIds.length}）</button><button data-action="repeatSession">🔄 再練同一組</button><button data-action="newQuiz">新的挑戰</button><button data-action="export">💾 備份</button></div></section><div class="section-head"><h2>📝 本次逐題回顧</h2></div><div class="score-list">${s.ids.map((id,i)=>{return quizQuestion(s,id,i);}).join('')}</div>`;}
function wrong(){let u=user();if(!u)return title('🌱','錯題澆水站','把不熟悉的地方，變成最牢固的知識。')+`<div class="empty"><div class="bigemoji">🌱</div><h2>先留下你的名字吧</h2><p>登入後，答錯的題目會自動收進這裡。</p><button class="primary" data-action="login">姓名登入</button></div>`;let ids=Object.keys(u.wrong).filter(id=>byId.has(id)&&(wrongAll||u.wrong[id].streak<2));return title('🌱','錯題澆水站','每題連續答對 2 次，就移入「已掌握」。曾經答錯的紀錄仍會保留。')+`<div class="toolbar"><button class="primary" data-action="practiceWrong" ${activeWrong().length?'':'disabled'}>💧 重練待加強 ${activeWrong().length} 題</button><button data-action="toggleWrong">${wrongAll?'只看待加強':'查看全部錯題歷史'}</button><button data-action="practiceAllWrong" ${Object.keys(u.wrong).length?'':'disabled'}>🔄 重練所有曾錯題</button></div><div class="learn-list">${ids.length?ids.map(id=>{let q=byId.get(id),w=u.wrong[id];return `<article class="card"><div class="ref muted">${esc(q.ref)} · ${w.streak>=2?'🌼 已掌握':'🌱 待加強'} · 累計錯 ${w.count} 次</div><h3>${esc(q.prompt)}</h3><p class="muted">最近錯答：${esc(w.last)}</p><div class="answer">正確：${esc(q.answer)}</div><p class="explain">${esc(q.explain)}</p><p class="muted">連續答對 ${w.streak} / 2 次</p><button class="tiny" data-practice-one="${id}">再練這一題</button></article>`;}).join(''):'<div class="empty full"><div class="bigemoji">🌷</div><h2>目前沒有待加強的題目</h2><p>可以開始測驗，或查看已掌握的錯題歷史。</p><button data-nav="quiz">去測驗 →</button></div>'}</div>`;}
function profile(){let u=user();if(!u)return (window.GardenCloud?.panel()||'')+title('🌻','我的複習帳本','每個名字，一份自己的進度。')+`<button class="primary" data-action="login">姓名登入</button>`;return (window.GardenCloud?.panel()||'')+title('🌻',`${esc(u.name)} 的複習帳本`,'保存努力，也為下一次複習留下線索。')+`<div class="card"><div class="actions"><button class="primary" data-action="export">💾 匯出我的全部進度</button><button data-action="import">📂 匯入進度</button><button data-cloud="recover">取出同步衝突備份</button><button data-action="login">👥 切換姓名</button><button data-action="logout">登出</button></div><p class="muted" style="margin:18px 0 0">備份包括姓名、已讀卡片、錯題紀錄、測驗成績與未完成作答。下載 JSON 後，在另一個裝置的相同網站匯入即可接續。清除瀏覽器資料會移除本機紀錄。</p></div><div class="section-head"><h2>🏅 測驗成績</h2><span class="muted">共 ${u.history.length} 次</span></div><div class="score-list">${u.history.map(h=>`<div class="history-row"><div><b>${esc(h.label)}</b><div class="muted">${new Date(h.at).toLocaleString('zh-TW')} · ${h.correct}/${h.total} 題 · ${formatTime(h.elapsed)}</div></div><strong>${h.score} 分</strong></div>`).join('')||'<div class="empty">🌼 還沒有完成的測驗，第一朵成績花等你來種。</div>'}</div>`;}
function exportData(){if(!requireUser())return;tick();persist();let blob=new Blob([JSON.stringify({format:'chinese-garden-backup',version:1,dataVersion:DATA.version,exported:new Date().toISOString(),user:user()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='國文小花園-進度備份.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),60000);toast('💾 備份已準備下載');}
function validateBackup(x){if(x?.format!=='chinese-garden-backup'||x.version!==1||x.dataVersion!==DATA.version)throw Error('備份格式或教材版本不符');let u=x.user;if(!u||typeof u.name!=='string'||!u.name.trim()||u.name.length>30||!Array.isArray(u.learned)||!Array.isArray(u.history)||!u.wrong||typeof u.wrong!=='object')throw Error('備份資料不完整');const valid=id=>typeof id==='string'&&byId.has(id);if(!u.learned.every(valid)||new Set(u.learned).size!==u.learned.length)throw Error('已讀紀錄有誤');const num=n=>Number.isFinite(n)&&n>=0;for(let [id,w] of Object.entries(u.wrong)){if(!valid(id)||!w||!Number.isInteger(w.count)||w.count<1||!Number.isInteger(w.streak)||w.streak<0||w.streak>2||typeof w.last!=='string')throw Error('錯題紀錄有誤');}for(let h of u.history){if(!h||typeof h.label!=='string'||!num(h.elapsed)||!Number.isInteger(h.total)||h.total<1||!Number.isInteger(h.correct)||h.correct<0||h.correct>h.total||h.score!==Math.round(h.correct/h.total*100)||isNaN(Date.parse(h.at)))throw Error('成績紀錄有誤');}let s=u.session;if(s){if(!Array.isArray(s.ids)||!s.ids.length||!s.ids.every(valid)||new Set(s.ids).size!==s.ids.length||!Number.isInteger(s.index)||s.index<0||s.index>=s.ids.length||!num(s.elapsed)||typeof s.label!=='string'||!s.answers||!s.order)throw Error('測驗進度有誤');if(s.optionBank){for(const id of s.ids){const opts=s.optionBank[id];if(!Array.isArray(opts)||opts.length!==4||new Set(opts).size!==4||!opts.every(o=>typeof o==='string'&&o.length<=1000))throw Error('備份選項資料有誤');}}for(let id of s.ids){if(!Array.isArray(s.order[id])||[...s.order[id]].sort().join(',')!=='0,1,2,3')throw Error('選項排序有誤');}for(let[id,a]of Object.entries(s.answers)){if(!s.ids.includes(id)||!a||!Number.isInteger(a.choice)||a.choice<0||a.choice>3||a.correct!==(a.choice===0))throw Error('作答紀錄有誤');}if(s.done&&(Object.keys(s.answers).length!==s.ids.length||s.score!==Math.round(Object.values(s.answers).filter(a=>a.correct).length/s.ids.length*100)))throw Error('完成成績有誤');s.paused=true;}return JSON.parse(JSON.stringify(u));}
$('#importFile').onchange=async e=>{let file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>5*1024*1024)throw Error('檔案超過 5MB');let u=validateBackup(JSON.parse(await file.text()));if(window.GardenCloud&&user()&&u.name!==user().name)throw Error('請先切換到「'+u.name+'」的名字，再匯入這份備份');confirmAction('匯入 '+u.name+' 的進度？','同名帳本會由此備份取代。若要保留目前紀錄，請先取消並匯出備份。',()=>{pause(false);db.users=db.users.filter(x=>x.name!==u.name);db.users.push(u);db.current=u.name;persist();navigate('profile');toast('已匯入，未完成測驗可繼續。');});}catch(err){toast('無法匯入：'+err.message);}};
function sources(){let d=DATA.sources.find(d=>d.id===sourceDoc);return title('🗂️','完整教材書架','四份 PDF 的 8 頁完整原稿，都能直接閱讀、放大核對。')+`<div class="source-tabs">${DATA.sources.map(d=>`<button class="${d.id===sourceDoc?'selected':''}" data-source="${d.id},1">${['🔑 注音國字答案','📝 注音國字題目','📒 重點彙整 1','📘 重點彙整 2'][d.id]}</button>`).join('')}</div><h3>${esc(d.name)}</h3><div class="source-tools"><button data-source="${sourceDoc},1" ${sourcePage===1?'disabled':''}>第 1 頁</button><button data-source="${sourceDoc},2" ${sourcePage===2?'disabled':''}>第 2 頁</button><button data-action="zoom">🔎 放大／符合寬度</button><a href="assets/doc${sourceDoc}-p${sourcePage}.jpg" target="_blank" rel="noopener">開啟原頁圖片 ↗</a><button data-nav="fill">填充解答</button><button data-nav="print">🖨️ 列印手寫考卷</button></div><div class="source-frame"><img class="source-image fit" src="assets/doc${sourceDoc}-p${sourcePage}.jpg" alt="${esc(d.name)} 第 ${sourcePage} 頁完整掃描"></div><div class="section-head"><h2>✅ 完整收錄核對表</h2></div><div class="table-wrap"><table><thead><tr><th>來源</th><th>內容範圍</th><th>網站收錄</th></tr></thead><tbody><tr><td>題目卷 1～2 頁</td><td>1～130 題，含多空格及跨頁續題</td><td>逐空學習卡＋單選題＋完整影像</td></tr><tr><td>答案卷 1～2 頁</td><td>1～130 題答案、131～135 補充；荼字及重門擊柝補充</td><td>對應答案、補充練習與原頁</td></tr><tr><td>重點彙整 1 第 1 頁</td><td>7 組形音義；大明湖複習提醒</td><td>逐組解釋、詞例、題庫與原頁</td></tr><tr><td>重點彙整 1 第 2 頁</td><td>第 1～10 題、兩闋詞默寫與比較</td><td>逐空補答、詞全文、題庫與原頁</td></tr><tr><td>重點彙整 2 第 1 頁</td><td>了／靡、鄉土詩、小說流變、詞簡介、詞派、詩詞格律</td><td>全部表格內容轉為學習卡及單選題</td></tr><tr><td>重點彙整 2 第 2 頁</td><td>報導文學、12 副人物聯、32 副行業聯</td><td>全部對聯、對應人物／行業、判讀提示及題庫</td></tr></tbody></table></div><div class="notice">📌 原講義另外提醒複習「課本 p.29、良師講義、習作 p.11、課本 p.174～175」。這些另冊頁面未包含在提供的四份 PDF 中，未冒稱已收錄。大明湖的景點順序、三副對聯文意、視聽覺景物等，請配合你的課本版本確認。</div><div class="section-head"><h2>🔎 補答與字詞核對來源</h2></div><div class="card small-links">${DATA.refs.map(([t,l])=>`<div><a href="${esc(l)}" target="_blank" rel="noopener">${esc(t)} ↗</a></div>`).join('')}<p class="muted">補答由教材語境整理，非原教師提供的標準答案。敘述性空格可有同義表述；網頁以明確單選方式練習。</p></div>`;}
function fill(){let groups=[...new Set(Q.filter(q=>q.fill).map(q=>q.fill))];return title('📝','填充解答小抄','對應重點彙整 1 第 2 頁的第 1～10 題，依原卷空格順序整理。')+`<div class="actions"><button data-source="2,2">🗂️ 對照原題</button><button data-topic-exact="填充解答">📚 逐空學習</button><button class="primary" data-action="practiceFill">🎯 填充轉選擇測驗</button></div><div class="notice">💡 下列是補寫解答。第 8 題的「寫景、抒情」與「敘事、議論」各對應兩格；第 9 題末空為文意題，接受合理同義說法。</div>${groups.map(g=>`<section class="card fill-group"><h3>${g==='1'?'🌾 ':g==='4'?'🌙 ':g==='9'?'🌈 ':g==='10'?'🏞️ ':''}原卷第 ${g} 題</h3><div class="table-wrap"><table><thead><tr><th>空格提示</th><th>補寫答案</th></tr></thead><tbody>${Q.filter(q=>q.fill===g).map(q=>`<tr><td>${esc(q.prompt)}</td><td class="fill-answer">${esc(q.answer)}<div class="muted" style="font-weight:400">${esc(q.explain)}</div></td></tr>`).join('')}</tbody></table></div></section>`).join('')}<div class="section-head"><h2>🌙 第 8 題・兩闋詞默寫</h2></div><div class="poems"><section class="card"><span class="tag">李煜 · 虞美人</span><div class="poem">春花秋月何時了？往事知多少。
小樓昨夜又東風，故國不堪回首月明中。
雕闌玉砌應猶在，只是朱顏改。
問君能有幾多愁？恰似一江春水向東流。</div><p class="muted">上片：美景與人事無常對比。下片：景物依舊與朱顏已改對比。設問與譬喻，抒發亡國之痛。</p></section><section class="card"><span class="tag">辛棄疾 · 南鄉子・登京口北固亭有懷</span><div class="poem">何處望神州？滿眼風光北固樓。
千古興亡多少事？悠悠，不盡長江滾滾流。
年少萬兜鍪，坐斷東南戰未休。
天下英雄誰敵手？曹劉，生子當如孫仲謀。</div><p class="muted">上片寫景抒情，下片敘事議論。三問三答，稱揚孫權以諷諫當朝，寄託抗金復國之志。</p></section></div>`;}
function bindPage(){let se=$('#search');if(se)se.oninput=e=>{search=e.target.value;pageIndex=0;let pos=e.target.selectionStart;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);};let ca=$('#category');if(ca)ca.onchange=e=>{category=e.target.value;pageIndex=0;render();};}
document.addEventListener('click',e=>{let b=e.target.closest('button,a');if(!b)return;
if(b.dataset.nav){e.preventDefault();navigate(b.dataset.nav);return;}if(b.dataset.source){e.preventDefault();[sourceDoc,sourcePage]=b.dataset.source.split(',').map(Number);navigate('sources');return;}if(b.dataset.loginIndex!==undefined){login(db.users[Number(b.dataset.loginIndex)].name);return;}if(b.dataset.topic){let cat=b.dataset.topic;category='主題・'+cat;pageIndex=0;search='';navigate('learn');return;}if(b.dataset.topicExact){category=b.dataset.topicExact;search='';pageIndex=0;navigate('learn');return;}
if(b.dataset.learned){if(!requireUser())return;let a=user().learned,id=b.dataset.learned;user().learned=a.includes(id)?a.filter(x=>x!==id):[...a,id];persist();render();return;}if(b.dataset.choice!==undefined){answer(Number(b.dataset.choice),b.dataset.question);return;}if(b.dataset.jump!==undefined){user().session.index=Number(b.dataset.jump);persist();render();return;}if(b.dataset.practiceOne){startSession([byId.get(b.dataset.practiceOne)],'單題澆水','all');return;}
const ac=b.dataset.action,s=user()?.session;switch(ac){case'login':openLogin();break;case'logout':if(window.GardenCloud){window.GardenCloud.leave();break;}pause(false);db.current=null;persist();navigate('home');break;case'reveal':showAllAnswers=!showAllAnswers;render();break;case'prevCards':pageIndex--;render();window.scrollTo(0,0);break;case'nextCards':pageIndex++;render();window.scrollTo(0,0);break;case'practiceFiltered':startSession(filtered(),'學習範圍：'+category,'all');break;case'practiceFill':startSession(topicRows('填充解答'),'填充解答與原題8默寫','all');break;case'start':{let c=$('#quizCategory').value;startSession(Q.filter(q=>matchesCategory(q,c)),c+'・完整單元','all');break;}case'firstUnanswered':firstUnanswered();break;case'pause':pause();render();break;case'resume':if(!requireUser())break;if(s&&!s.done){s.paused=false;lastTick=Date.now();persist();navigate('quiz');scrollQuestion(s.ids[s.index]);}break;case'newQuiz':{let clear=()=>{user().session=null;persist();navigate('quiz');};if(s&&!s.done)confirmAction('另開新測驗？','這次未完成的進度會被取代，錯題與過往成績會保留。',clear);else clear();break;}case'prevQ':s.index--;persist();render();break;case'nextQ':if(s.index<s.ids.length-1){s.index++;persist();render();}else finish();break;case'finish':finish();break;case'retrySessionWrong':startSession(s.ids.filter(id=>!s.answers[id].correct).map(id=>byId.get(id)),'本次錯題重練','all');break;case'repeatSession':startSession(s.ids.map(id=>byId.get(id)),'同組再練','all');break;case'practiceWrong':startSession(activeWrong().map(id=>byId.get(id)),'錯題澆水練習','all');break;case'practiceAllWrong':startSession(Object.keys(user().wrong).filter(id=>byId.has(id)).map(id=>byId.get(id)),'錯題歷史複習','all');break;case'toggleWrong':wrongAll=!wrongAll;render();break;case'export':exportData();break;case'import':$('#importFile').click();break;case'zoom':$('.source-image').classList.toggle('fit');break;}
});
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||document.querySelector('dialog[open]'))return;const s=user()?.session,card=e.target.closest?.('[data-question-card]');if(view==='quiz'&&card&&s&&!s.done&&!s.paused&&/^[1-4]$/.test(e.key)){const id=card.dataset.questionCard;answer(s.order[id][Number(e.key)-1],id);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause(false);}else{lastTick=Date.now();if(view==='quiz')render();}});
window.addEventListener('pagehide',()=>{pause(false);persist();});
setInterval(()=>{tick();if($('#timer')&&user()?.session)$('#timer').textContent=formatTime(user().session.elapsed);},1000);
setInterval(()=>{if(user()?.session&&!user().session.paused)persist();},10000);
if(user()?.session&&!user().session.done)user().session.paused=true;
persist();updateUser();render();

function printPage(){return title('🖨️','紙筆練習小教室','把字親手寫下來，記憶更牢固。A4 直式，題目卷與答案卷逐頁對應。')+`<div class="notice">完整收錄原題 1～130 與補充 131～135，共 231 小題。每份 7 頁，每頁最多 34 小題，雙欄排版並保留手寫橫線。「原題號－小題序」方便對照教材。</div><div class="poems"><section class="card center"><div class="bigemoji">📝</div><h2>手寫題目卷</h2><p class="muted">答案留白，適合自我檢測與正式練習。</p><div class="actions" style="justify-content:center"><a class="primary print-link" href="print-questions.html" target="_blank" rel="noopener">開啟列印預覽</a><a class="print-link" href="print-questions.pdf" download>下載題目 PDF ↓</a></div></section><section class="card center"><div class="bigemoji">🔑</div><h2>對照答案卷</h2><p class="muted">相同題序與版面，答案填在相同位置。</p><div class="actions" style="justify-content:center"><a class="primary print-link" href="print-answers.html" target="_blank" rel="noopener">開啟列印預覽</a><a class="print-link" href="print-answers.pdf" download>下載答案 PDF ↓</a></div></section></div><section class="card" style="margin-top:22px"><h3>🌼 列印小提醒</h3><p>開啟 PDF 直接列印，或進入預覽頁按「列印這份考卷」。選擇 <b>A4、直式、100% 大小</b>；網頁列印時關閉瀏覽器頁首與頁尾。</p><p class="muted">紙本作答不會自動加入網頁成績。批改後，可用原題號在學習區搜尋，再進行線上練習。</p></section>`;}

if(typeof ResizeObserver!=='undefined'){new ResizeObserver(entries=>{document.documentElement.style.setProperty('--header-height',entries[0].target.getBoundingClientRect().height+'px');}).observe(document.querySelector('header'));}
